### ISSUE TITLE
Early commit for Hello World on UART

### ISSUE THREAD

**Issue by utpalsolanki** [dragon-ware/base#1]
@meetbshah 
I have assigned this first issue. Whenever you get time, please prepare Hello World on UART in bare-metal fashion. Keep committing code and push so that I can also look at it.

**Comment by utpalsolanki** [comment]
@meetbshah  you can see that this issue number is "#1", if you include this issue number in your commit message, it will automatically link your push to this issue, as you can see above how my early  commit referenced here. 
We should always reference issue number in each commit message.

**Comment by meetbshah** [comment]
@utpalsolanki Review it and give your feedback.

**Comment by utpalsolanki** [comment]
Awesome, I will create another issue for code clean up and have it assigned to me.
